# Generated by Django 5.2.1 on 2025-06-02 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('aniversario', models.DateField()),
                ('jefe_grado', models.CharField(max_length=50)),
                ('jefe_nombre', models.CharField(max_length=100)),
                ('jefe_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EfectivoPlantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hombres', models.PositiveIntegerField()),
                ('mujeres', models.PositiveIntegerField()),
                ('plantel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efectivo', to='planteles.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Posgrado', 'Posgrado')], max_length=20)),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_estudio', to='planteles.plantel')),
            ],
        ),
    ]
