# Generated by Django 5.2.1 on 2025-06-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EntidadFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipoestudio',
            name='plantel',
        ),
        migrations.RemoveField(
            model_name='plantel',
            name='aniversario',
        ),
        migrations.RemoveField(
            model_name='plantel',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='plantel',
            name='jefe_grado',
        ),
        migrations.RemoveField(
            model_name='plantel',
            name='jefe_nombre',
        ),
        migrations.RemoveField(
            model_name='plantel',
            name='jefe_telefono',
        ),
        migrations.AddField(
            model_name='plantel',
            name='cursos',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantel',
            name='duracion_curso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantel',
            name='tipo_estudio',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('antiguedad', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.categoriadiscente')),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.plantel')),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.entidadfederativa')),
            ],
        ),
        migrations.CreateModel(
            name='CasoMedicoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caso', models.DateField()),
                ('descripcion', models.TextField()),
                ('acciones_adoptadas', models.TextField()),
                ('id_discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.discente')),
            ],
        ),
        migrations.CreateModel(
            name='EfectivoDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_hombre', models.IntegerField()),
                ('cant_mujer', models.IntegerField()),
                ('cant_total', models.IntegerField()),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_egreso', models.DateField()),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='EfectivoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('fecha_registro', models.DateField()),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.plantel')),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.entidadfederativa')),
            ],
        ),
        migrations.CreateModel(
            name='Infresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('id_plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.plantel')),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField()),
                ('id_discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.discente')),
                ('id_tipo_baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.tipobaja')),
            ],
        ),
        migrations.DeleteModel(
            name='EfectivoPlantel',
        ),
        migrations.DeleteModel(
            name='TipoEstudio',
        ),
    ]
