# Generated by Django 5.2.1 on 2025-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0002_categoriadiscente_entidadfederativa_tipobaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
