# Generated by Django 5.2.1 on 2025-06-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0003_alter_discente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='discente',
            name='matricula',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
