# Generated by Django 5.2.1 on 2025-06-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0004_discente_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efectivodiscente',
            name='cant_hombre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='efectivodiscente',
            name='cant_mujer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='efectivodiscente',
            name='cant_total',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EfectivoCasoMedicoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_hombre', models.IntegerField(default=0)),
                ('cant_mujer', models.IntegerField(default=0)),
                ('cant_total', models.IntegerField(default=0)),
                ('id_plantel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planteles.plantel')),
            ],
        ),
    ]
