# Generated by Django 5.2.1 on 2025-06-04 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0006_remove_tipobaja_motivo_tipobaja_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baja',
            old_name='id_tipo_baja',
            new_name='tipo_baja',
        ),
        migrations.AddField(
            model_name='baja',
            name='motivo',
            field=models.TextField(default='no especificado'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EfectivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_hombre', models.PositiveIntegerField(default=0)),
                ('cant_mujer', models.PositiveIntegerField(default=0)),
                ('cant_total', models.PositiveIntegerField(default=0)),
                ('id_plantel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planteles.plantel')),
            ],
        ),
    ]
